### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by Akuukis** [benreid24/Stellaru#133]
The leaderboard section is a lot of new features, which did work for my playthrough good. If you waited for me to confirm that before a new release then here I go - it's working, thank you a lot! :)

**Comment by Akuukis** [comment]
@benreid24 can you please review/merge https://github.com/benreid24/Stellaru/pull/132 into the new release.

Sadly the only way to setup Stellaru for me (or my friends) is via Ubuntu, checkout that PR, build and run locally. That weirdly doesn't work on windows because it can't find and/or follow new saves (imho fails to watch the folder, or the correct folder, but idk). That leaves out windows users unable to use new leaderboards.

I'm happy to help you with maintaining the repo and releases if you wish. But in that case readme only lacks information how to create and publish a release.

**Comment by benreid24** [comment]
Sorry for the delay, been real busy with life, work, and other projects. Just cut a release!
