### ISSUE TITLE
getting KeyError: 'name' on savegame load. 

### ISSUE THREAD

**Issue by Xelan256** [benreid24/Stellaru#150]
Hi,

I wanted to give this a try today, downloaded the latest release and extracted it. But ran into an issue after trying to select a savegame. Screensots from the console below:

![2023-03-26 16_51_12-F__Programme_Stellaru_Stellaru exe](https://user-images.githubusercontent.com/128986859/227797231-576c7942-ba09-4c77-993c-b9218906c8d7.jpg)
![2023-03-26 16_51_34-F__Programme_Stellaru_Stellaru exe](https://user-images.githubusercontent.com/128986859/227797234-db13e97e-3130-45ba-9917-010863aafbc4.jpg)

No idea here the path "D:\a\[...]" comes from, that doesn't exist. I guess the error comes from that. Stellaru, as well as Stellaris are installed on F:\.

**Comment by Akuukis** [comment]
Should be fixed by https://github.com/benreid24/Stellaru/pull/151

**Comment by benreid24** [comment]
Looks like it is
