### ISSUE TITLE
Problem loading module channels.staticfiles on v3.0.11 

### ISSUE THREAD

**Issue by DanielYurystovskyi** [benreid24/Stellaru#157]
![image](https://github.com/user-attachments/assets/ac7ee708-e7f8-44f9-8e9a-932a04a36689)
[v3.0.8](https://github.com/benreid24/Stellaru/releases/tag/v3.0.8) works fine

**Comment by benreid24** [comment]
Published a new release with the fix!

https://github.com/benreid24/Stellaru/releases/tag/v3.0.12
