### ISSUE TITLE
Overwrite Data?

### ISSUE THREAD

**Issue by Romanophile** [benreid24/Stellaru#159]
Is it possible to get the program to overwrite data if you go back? I tend to save and reload a lot but it keeps data from the first save at that specific time and so can become inaccurate pretty quickly. Is there a way to overwrite data at specific time points?

**Comment by benreid24** [comment]
Hello. Currently the Stellaru data model is append-only when new saves are loaded. With some work it could probably be made to support purging of out-of-order snapshots. I can take a look into that sometime this week.

**Comment by benreid24** [comment]
Newer save files with older in-game dates will now result in the sequence of data being rewritten. Published https://github.com/benreid24/Stellaru/releases/tag/v3.1.0 with the change.
