### ISSUE TITLE
Error loading save: RecursionError('maximum recursion depth exceeded in comparison')

### ISSUE THREAD

**Issue by Ash19256** [benreid24/Stellaru#38]
I received this error during an initial test with a heavily modded save. I'm uncertain as to the cause. Included are the save which triggered the error, as well as the list of mods (as provided by the [Paradox Mod Manager utility](https://github.com/ThibautSF/ParadoxosModManagerRework/).

[Export_Stellaris_27 List-ErrorModList.zip](https://github.com/benreid24/Stellaru/files/5432474/Export_Stellaris_27.List-ErrorModList.zip)
[2302.07.27-ErrorSaveFile.zip](https://github.com/benreid24/Stellaru/files/5432471/2302.07.27-ErrorSaveFile.zip)

**Comment by benreid24** [comment]
Thanks for the details! I believe mods have been causing issues for other players as well, hoping to get a patch out soon

**Comment by benreid24** [comment]
Able to reproduce with the supplied save. The error appears to be with my custom parser. The supplied save is quite a bit larger than any I tested with. Will have to rewrite the parser to be iterative instead of recursive
