### ISSUE TITLE
Dockerizing Stellaru

### ISSUE THREAD

**Issue by primetoxinz** [benreid24/Stellaru#42]
Hello,

I have been using Stellaru in my most recent mp game with friends, its great to have the introspection. Since my desktop is linux, I was just running the dev servers manually. I decided today to dockerize the application and mount in the saves for it to access and I got it fully working.

I was wondering if you'd be interested in having the Dockerfile and such.

Also, are you in any public chats (ie discord)? I'm definitely interested in assisting more with this project.

**Comment by benreid24** [comment]
Hey, so happy you're interested! There aren't any public chats or anything as this has just been a side project of mine for a few months. I'd love to have contributions from others, this is definitely something I want to keep up with and continue adding more features. Right now everything is in a paper notebook, so I may take some time soon to either make issues or try out the Projects feature on Github.

As for Docker, I'm certainly not opposed. Docker would provide an easier way for developers to test Linux/Windows versions from just one machine. I would think that each platform would need it's own Dockerfile though as the saves are in different locations. The volume mounts would need to change. Feel free to open a PR with your Dockerfile, I'd be happy to try it out!

**Comment by benreid24** [comment]
Going to close this for now, I don't think docker is on the radar at the moment
