### ISSUE TITLE
Idea: Colony stats scatterplot view

### ISSUE THREAD

**Issue by boterham** [benreid24/Stellaru#58]
I've been using Stellaru a lot to keep track of my colonies' amenities, stability, and other variables that can turn problematic if neglected. The current line chart legend can get very crowded if you have a healthy number of colonies, and I think it would be fantastic to have scatterplots of your colonies with two user-defined variables on the X and Y axis.

**Comment by benreid24** [comment]
Great idea! I agree that the chart becomes very crowded once you have a good set of colonies. I tested with a Determined Exterminator empire and having 100+ planets was a bit much.

I'm thinking two dropdowns to select the stats for the X and Y axes. Will add this to the todo list
