### ISSUE TITLE
Galatic Market

### ISSUE THREAD

**Issue by noah427** [benreid24/Stellaru#63]
I know you guys don't officially support linux yet but I use linux and I couldn't resist trying it out. All the galactic market prices are the base prices and don't change when they change in game. 

My terminal output looks like this.

daphne/server.py:11: UserWarning: Something has already installed a non-asyncio Twisted reactor. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.
No changes detected
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
Starting Stellaru

(firefoxdeveloperedition:33024): Gtk-WARNING **: 21:02:37.246: Theme parsing error: gtk.css:2:33: Failed to import: Error opening file /home/noah/.config/gtk-3.0/window_decorations.css: No such file or directory
Session YAR4XR9816GTN1HCE1O4AC0KIT9TZTVL connected
  File "stellaru_api/views.py", line 25, in get_translations
Message received: Client: YAR4XR9816GTN1HCE1O4AC0KIT9TZTVL Content: {'message': 'Frontend connected'}
Message received: Client: YAR4XR9816GTN1HCE1O4AC0KIT9TZTVL Content: {'subscribe': {}}
Message received: Client: YAR4XR9816GTN1HCE1O4AC0KIT9TZTVL Content: {'subscribe': {}}
Message received: Client: YAR4XR9816GTN1HCE1O4AC0KIT9TZTVL Content: {'subscribe': {}}
Message received: Client: YAR4XR9816GTN1HCE1O4AC0KIT9TZTVL Content: {'subscribe': {}}
Message received: Client: YAR4XR9816GTN1HCE1O4AC0KIT9TZTVL Content: {'subscribe': {}}
Warning: Failed to get market prices for 0 (Monopoly), using base prices
Warning: Failed to get market prices for 13 (Vrinn Archivists), using base prices
Warning: Failed to get market prices for 14 (Triech Shard), using base prices
Warning: Failed to get market prices for 15 (Pelx-Cradonian Forerunners), using base prices
Warning: Failed to get market prices for 167772185 (Tebadoran Mercantile Guilds), using base prices

**Comment by benreid24** [comment]
Thanks for the report! Is this a new save? Would you mind sharing your gamesave if possible so I may debug this? If everything else is working on Linux for you then I think we're good there. The market prices are a new addition, so it's more than likely I made a mistake in there.

**Comment by noah427** [comment]
The save isn't new. I tried the tool on it midgame. It seems to have the issue on all my saves. This is the save I used for the terminal log I sent you. 
[monopoly.zip](https://github.com/benreid24/Stellaru/files/5576930/monopoly.zip)

**Comment by benreid24** [comment]
Looking through the save data, your empire does not have any internal market fluctuations, which causes the market price extractor to error out. I have fixed the issue with that and will cut a release shortly. Did you make any transactions in the market somewhat recently? Are you a participant in the galactic market (if it exists yet)?

**Comment by noah427** [comment]
I was participating in the galactic market and I was buying and selling quite a bit there.

**Comment by benreid24** [comment]
Got it. The fix should work for you. The problem was Stellaru was assuming that each empire would have internal market fluctuations (price fluctuation before joining Galactic Market), however this isn't always true. The fix addresses that by having it check before accessing.

The fix is in the [latest release](https://github.com/benreid24/Stellaru/releases/tag/v1.3.0)

**Comment by noah427** [comment]
Thanks! I appreciate your work.
