### ISSUE TITLE
Constant resizing in browser view

### ISSUE THREAD

**Issue by prkerrigan** [benreid24/Stellaru#76]
when I load the stellaru window in chrome the Waiting (Connected)... bar/icon constantly jumps between two indentation states which is incredibly annoying when your trying to look at a graph and its resizing every few seconds. Can be fixed by adjusting zoom level but ideally this would not happen at any scale.

**Comment by benreid24** [comment]
Sounds like the text in the box gets too big and wraps onto a new line?

**Comment by benreid24** [comment]
Cut a new release for you with the fix: https://github.com/benreid24/Stellaru/releases/tag/v2.0.2

Thanks for pointing that out!

**Comment by prkerrigan** [comment]
wow, awesome turn around, yes that is what is happening. Thank you!
