### ISSUE TITLE
Build science leaderboard chart

### ISSUE THREAD

**Issue by benreid24** [benreid24/Stellaru#97]
Unsure of what exactly would be interesting for this to track. Total science output per month would be a good metric. Graphing overall technical progress is trickier though. Simply summing the researched techs in each group is not be a great indicator of comparative progress and simply favors larger groups, even if they have the same tech level as smaller groups. Comparing tech level may require more data extraction from the save. It may also be possible to take the highest technology victory score from each group and graph that as a representation of the tech level of each group.

Another interesting idea, not necessarily just for this chart, would be to allow users to choose whether to graph totals or to graph averages for each group/federation.

**Comment by Akuukis** [comment]
Researched techs for individuals is fine. For group/federations, let's use average researched techs (total researched techs divided by amount of players)?

An even better metric than "researched techs" is total base cost of researched techs (aka research value?) - that wouldn't bias that much towards cheaper techs.
